package model;
// Generated Mar 7, 2018 2:00:43 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Author generated by hbm2java
 */
public class Author  implements java.io.Serializable {


     private String authorId;
     private String author;
     private Set<Book> books = new HashSet<Book>(0);

    public Author() {
    }

	
    public Author(String authorId) {
        this.authorId = authorId;
    }
    public Author(String authorId, String author, Set<Book> books) {
       this.authorId = authorId;
       this.author = author;
       this.books = books;
    }
   
    public String getAuthorId() {
        return this.authorId;
    }
    
    public void setAuthorId(String authorId) {
        this.authorId = authorId;
    }
    public String getAuthor() {
        return this.author;
    }
    
    public void setAuthor(String author) {
        this.author = author;
    }
    public Set<Book> getBooks() {
        return this.books;
    }
    
    public void setBooks(Set<Book> books) {
        this.books = books;
    }




}


