package model;
// Generated Mar 7, 2018 2:00:43 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Book generated by hbm2java
 */
public class Book  implements java.io.Serializable {


     private String bookId;
     private Author author;
     private Genre genre;
     private String title;
     private String synopsis;
     private Integer year;
     private Integer page;
     private Integer price;
     private Set<TransList> transLists = new HashSet<TransList>(0);

    public Book() {
    }

	
    public Book(String bookId) {
        this.bookId = bookId;
    }
    public Book(String bookId, Author author, Genre genre, String title, String synopsis, Integer year, Integer page, Integer price, Set<TransList> transLists) {
       this.bookId = bookId;
       this.author = author;
       this.genre = genre;
       this.title = title;
       this.synopsis = synopsis;
       this.year = year;
       this.page = page;
       this.price = price;
       this.transLists = transLists;
    }
   
    public String getBookId() {
        return this.bookId;
    }
    
    public void setBookId(String bookId) {
        this.bookId = bookId;
    }
    public Author getAuthor() {
        return this.author;
    }
    
    public void setAuthor(Author author) {
        this.author = author;
    }
    public Genre getGenre() {
        return this.genre;
    }
    
    public void setGenre(Genre genre) {
        this.genre = genre;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getSynopsis() {
        return this.synopsis;
    }
    
    public void setSynopsis(String synopsis) {
        this.synopsis = synopsis;
    }
    public Integer getYear() {
        return this.year;
    }
    
    public void setYear(Integer year) {
        this.year = year;
    }
    public Integer getPage() {
        return this.page;
    }
    
    public void setPage(Integer page) {
        this.page = page;
    }
    public Integer getPrice() {
        return this.price;
    }
    
    public void setPrice(Integer price) {
        this.price = price;
    }
    public Set<TransList> getTransLists() {
        return this.transLists;
    }
    
    public void setTransLists(Set<TransList> transLists) {
        this.transLists = transLists;
    }




}


