package model;
// Generated Mar 7, 2018 2:00:43 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Genre generated by hbm2java
 */
public class Genre  implements java.io.Serializable {


     private String genreId;
     private String genre;
     private Set<Book> books = new HashSet<Book>(0);

    public Genre() {
    }

	
    public Genre(String genreId) {
        this.genreId = genreId;
    }
    public Genre(String genreId, String genre, Set<Book> books) {
       this.genreId = genreId;
       this.genre = genre;
       this.books = books;
    }
   
    public String getGenreId() {
        return this.genreId;
    }
    
    public void setGenreId(String genreId) {
        this.genreId = genreId;
    }
    public String getGenre() {
        return this.genre;
    }
    
    public void setGenre(String genre) {
        this.genre = genre;
    }
    public Set<Book> getBooks() {
        return this.books;
    }
    
    public void setBooks(Set<Book> books) {
        this.books = books;
    }




}


