package model;
// Generated Apr 26, 2018 6:51:31 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Status generated by hbm2java
 */
public class Status  implements java.io.Serializable {


     private String statusId;
     private String status;
     private String statusDesc;
     private Set<Transactions> transactionses = new HashSet<Transactions>(0);

    public Status() {
    }

	
    public Status(String statusId) {
        this.statusId = statusId;
    }
    public Status(String statusId, String status, String statusDesc, Set<Transactions> transactionses) {
       this.statusId = statusId;
       this.status = status;
       this.statusDesc = statusDesc;
       this.transactionses = transactionses;
    }
   
    public String getStatusId() {
        return this.statusId;
    }
    
    public void setStatusId(String statusId) {
        this.statusId = statusId;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getStatusDesc() {
        return this.statusDesc;
    }
    
    public void setStatusDesc(String statusDesc) {
        this.statusDesc = statusDesc;
    }
    public Set<Transactions> getTransactionses() {
        return this.transactionses;
    }
    
    public void setTransactionses(Set<Transactions> transactionses) {
        this.transactionses = transactionses;
    }




}


