package model;
// Generated Mar 7, 2018 2:00:43 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Transaction generated by hbm2java
 */
public class Transaction  implements java.io.Serializable {


     private String transId;
     private Customer customer;
     private Status status;
     private Date transDate;
     private Set<TransList> transLists = new HashSet<TransList>(0);

    public Transaction() {
    }

	
    public Transaction(String transId, Date transDate) {
        this.transId = transId;
        this.transDate = transDate;
    }
    public Transaction(String transId, Customer customer, Status status, Date transDate, Set<TransList> transLists) {
       this.transId = transId;
       this.customer = customer;
       this.status = status;
       this.transDate = transDate;
       this.transLists = transLists;
    }
   
    public String getTransId() {
        return this.transId;
    }
    
    public void setTransId(String transId) {
        this.transId = transId;
    }
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }
    public Status getStatus() {
        return this.status;
    }
    
    public void setStatus(Status status) {
        this.status = status;
    }
    public Date getTransDate() {
        return this.transDate;
    }
    
    public void setTransDate(Date transDate) {
        this.transDate = transDate;
    }
    public Set<TransList> getTransLists() {
        return this.transLists;
    }
    
    public void setTransLists(Set<TransList> transLists) {
        this.transLists = transLists;
    }




}


