package model;
// Generated Apr 4, 2018 9:47:59 PM by Hibernate Tools 4.3.1



/**
 * TransListsId generated by hbm2java
 */
public class TransListsId  implements java.io.Serializable {


     private String transId;
     private String bookId;

    public TransListsId() {
    }

    public TransListsId(String transId, String bookId) {
       this.transId = transId;
       this.bookId = bookId;
    }
   
    public String getTransId() {
        return this.transId;
    }
    
    public void setTransId(String transId) {
        this.transId = transId;
    }
    public String getBookId() {
        return this.bookId;
    }
    
    public void setBookId(String bookId) {
        this.bookId = bookId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TransListsId) ) return false;
		 TransListsId castOther = ( TransListsId ) other; 
         
		 return ( (this.getTransId()==castOther.getTransId()) || ( this.getTransId()!=null && castOther.getTransId()!=null && this.getTransId().equals(castOther.getTransId()) ) )
 && ( (this.getBookId()==castOther.getBookId()) || ( this.getBookId()!=null && castOther.getBookId()!=null && this.getBookId().equals(castOther.getBookId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getTransId() == null ? 0 : this.getTransId().hashCode() );
         result = 37 * result + ( getBookId() == null ? 0 : this.getBookId().hashCode() );
         return result;
   }   


}


