package model;
// Generated Mar 7, 2018 2:00:43 PM by Hibernate Tools 4.3.1



/**
 * TransList generated by hbm2java
 */
public class TransList  implements java.io.Serializable {


     private TransListId id;
     private Book book;
     private Transaction transaction;
     private Integer quantity;

    public TransList() {
    }

	
    public TransList(TransListId id, Book book, Transaction transaction) {
        this.id = id;
        this.book = book;
        this.transaction = transaction;
    }
    public TransList(TransListId id, Book book, Transaction transaction, Integer quantity) {
       this.id = id;
       this.book = book;
       this.transaction = transaction;
       this.quantity = quantity;
    }
   
    public TransListId getId() {
        return this.id;
    }
    
    public void setId(TransListId id) {
        this.id = id;
    }
    public Book getBook() {
        return this.book;
    }
    
    public void setBook(Book book) {
        this.book = book;
    }
    public Transaction getTransaction() {
        return this.transaction;
    }
    
    public void setTransaction(Transaction transaction) {
        this.transaction = transaction;
    }
    public Integer getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }




}


